### ISSUE TITLE
Data management (SuperSet)

### ISSUE THREAD

**Issue by clement-igonet** [event-driven-io/Pongo#14]
MongoDB is not supported by Apache SuperSet. Relational DB like PostgreSQL is.

Would Pongo help in fixing this issue ?

**Comment by oskardudycz** [comment]
I'm not an expert with Apache SuperSet, but based on my research, it supports PostgreSQL JSONB queries, so it should work well as Pongo is _just_ a wrapper on top of regular PostgreSQL.

Could you tell me more about your use case? 🙂

**Comment by oskardudycz** [comment]
@clement-igonet, I'm closing it for now, feel free to ask follow up questions if you have more :slightly_smiling_face:
