### ISSUE TITLE
Spport creating pongoClient without connection pool

### ISSUE THREAD

**Issue by OilyLime** [event-driven-io/Pongo#35]
Hey @oskardudycz 👋 

Very cool project. I work on [Cloudflare Hyperdrive](https://developers.cloudflare.com/hyperdrive/) (a service for connecting to Postgres databases from Cloudflare's Workers serverless platform) and would love to get Pongo to work with our service.

Our service already offers connection pooling (optionally caching too) so it would be interesting if Pongo allowed an option to disable connection pooling in the client.

In general, folks might not want to pool connections from a serverless environment.

**Comment by oskardudycz** [comment]
Hey @OilyLime, thank you for the interest. I, of course, know Cloudflare Hyperdrive, and it's on my radar to ensure support for it :) I just added the capability to use the regular (non-pooled) client: https://github.com/event-driven-io/Pongo/pull/38.

If you're open, I'd be happy to jump on the call to understand the need and see if I could make Pongo better to ensure it works well with Hyperdrive. Are you open to that? I'm also happy to take contribution or other form of support :slightly_smiling_face: 

I'd also be interested in getting some guidance on how to set up GH Actions to run continuous tests and ensure that it works well with Hyperdrive.

Thank you in advance for the follow-up on the changes in 0.8.0 that covered your needs :slightly_smiling_face: 

p.s. apologies for delayed answer, I was on 2-week vacations trying to disconnect a bit from the Internet noise.
